language: node_js
node_js:
  - '10'
say_hi_:):
  - echo "hey blue It's deploying now !"
install:
  - npm install -g firebase-tools
  - npm install
build:
  - npm run build
deploy_to_firebase:
  - firebase deploy --token $FIREBASE_TOKEN
