language: node_js
node_js:
  - '10'
script:
  - echo "hey blue It's deploying now !"
install:
  - npm install -g firebase-tools
  - npm install
  - npm run build
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
